### ISSUE TITLE
Colorscheme looks weird in Go

### ISSUE THREAD

**Issue by msal4** [skbolton/embark#1]
### After enabling embark, this is how it looks in a Go file.
<img width="1440" alt="Screen Shot 2020-07-10 at 1 11 29 AM" src="https://user-images.githubusercontent.com/30052233/87095962-75ec2480-c24a-11ea-94bd-a866bc0ee0be.png">

**Comment by skbolton** [comment]
Looks like you don't have truecolor turned on. Did you `set termguicolor` in your vimrc

**Comment by msal4** [comment]
Yes, it looks the same.

**Comment by skbolton** [comment]
what terminal are you using?

**Comment by msal4** [comment]
iTerm

**Comment by msal4** [comment]
iTerm

**Comment by skbolton** [comment]
Does the syntax look weird in all filetypes? Like markdown and whatnot?

**Comment by skbolton** [comment]
Also has your vimrc changed from whats [here](https://github.com/msal4/vimrc)? You don't have termguicolors enabled in that rc

**Comment by msal4** [comment]
After setting `termguicolors` it looks different but the comments are highlighted. are they supposed to look like this?

<img width="1440" alt="Screen Shot 2020-07-10 at 9 33 45 PM" src="https://user-images.githubusercontent.com/30052233/87187291-99b87480-c2f5-11ea-9187-33993de22c7b.png">

yes it looks the same on other types of files
<img width="1154" alt="Screen Shot 2020-07-10 at 9 34 59 PM" src="https://user-images.githubusercontent.com/30052233/87188639-ddac7900-c2f7-11ea-91bb-32ee1458c26d.png">

**Comment by skbolton** [comment]
Those are italics. You can either follow the guide [here](https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be) to get italics and true color working. Or disable italics in the theme by setting `let g:embark_terminal_italics = 0`. These are details I an working on documenting better for this repo.

**Comment by msal4** [comment]
thanks, it's looking good now:)
