### ISSUE TITLE
Sharing: Kitty terminal embark theme config file

### ISSUE THREAD

**Issue by pyrho** [skbolton/embark#10]
Here is a theme file for the [kitty](https://sw.kovidgoyal.net/kitty/) terminal emulator that matches colors from embark.
```conf
# Embark (https://github.com/skbolton/embark/) {{{
background #1e1c31
foreground #EEFFFF
cursor #A1EFD3
selection_background  #fbfcfc

# black
color0 #1e1c31
color8 #3E3859

# red
color1 #F0719B
color9 #F02E6E

# green
color2 #A1EFD3
color10 #2CE592

# yellow
color3       #ffe9aa
color11      #ffb378

# blue
color4 #57C7FF
color12 #1DA0E2

# magenta
color5 #C792EA
color13 #A742EA

# cyan
color6       #87DFEB
color14      #63f2f1

# white
color7 #F8F8F2
color15 #a6b3cc


active_border_color #A1EFD3
inactive_border_color #a6b3cc
bell_border_color #f56574

active_tab_foreground   #222433 
active_tab_background   #63f2f1
active_tab_font_style   bold

inactive_tab_foreground #63f2f1
inactive_tab_background #222433 
inactive_tab_font_style normal

# }}}
```

It looks like this:
<img width="1104" alt="Screenshot 2020-08-18 at 01 47 37" src="https://user-images.githubusercontent.com/145502/90454918-d8133180-e0f4-11ea-9418-f7a7777d486d.png">

Maybe this could be an entry in the wiki ?

**Comment by skbolton** [comment]
In the next few days I am going to move this repo to the `embark-theme` organization that way I can host all the ports in one spot. I so far have a kitty theme, spicetify theme, and a bashtop theme on top of the vim theme

**Comment by skbolton** [comment]
I don't use tabs in Kitty though so I might have to steal that tab configuration you have there. Look out for the organization and that separate repo.

**Comment by skbolton** [comment]
Sneak Peek! :)
![DeepinScreenshot_select-area_20200817180629](https://user-images.githubusercontent.com/13260877/90455812-48e62980-e0b4-11ea-8f0f-2ba7c5e90d00.png)

**Comment by skbolton** [comment]
Sorry for my blasting of comments here 😄  . I went ahead and created the repo for the kitty fork [here](https://github.com/embark-theme/kitty). Feel free to open a PR there with what you have here.

**Comment by pyrho** [comment]
Great initiative ! I'll close this issue then.

ps: cool setup !, what's the "top" utility you're using on the left there ?

**Comment by skbolton** [comment]
Thats bashtop! Easily the prettiest terminal application output I have seen

**Comment by pyrho** [comment]
> Thats bashtop! Easily the prettiest terminal application output I have seen

fuck yea, those GUI folks have nothing on bashtop (:
