### ISSUE TITLE
line number contrast isn't fantastic

### ISSUE THREAD

**Issue by imajes** [skbolton/embark#4]
Is there any chance to make an option to boost the contrast of the line numbers? :) 

thanks, love the scheme. :)

**Comment by skbolton** [comment]
Yeah this is one that I figured would come up. I think a configuration to boost the value by a percentage would be a good option.

**Comment by skbolton** [comment]
So I am leaning towards offering three variants on this. Let me know what you think about these colors. The soft variant would be what it is today. The default variant would be `#585273` and the hard variant would be `#716B8C`.

To try any of these out you can call `hi LineNr guifg=#585273` anywhere after you have set the embark colorscheme, and of course you would just change that color code to whatever you want to test out.

**Comment by skbolton** [comment]
Here are quick previews of the above codes though

Soft (current)
<img width="776" alt="soft" src="https://user-images.githubusercontent.com/13260877/89698841-9a3a3000-d8e0-11ea-9e1d-48eb85127bae.png">

Default (10% brighter)
<img width="788" alt="default" src="https://user-images.githubusercontent.com/13260877/89698848-a625f200-d8e0-11ea-811d-0856cec2252a.png">

hard (20% brighter)
<img width="784" alt="hard" src="https://user-images.githubusercontent.com/13260877/89698852-afaf5a00-d8e0-11ea-8fa2-0eff18a59a20.png">

**Comment by imajes** [comment]
I like default. what's doing your active line-highlighting?

**Comment by skbolton** [comment]
I have created the branch `linenr-contrast` which changes the linenr to be that default color if you want to point your packager to that branch.

As far as the cursorline that is configured in the theme you just have to turn it on in vim `set cursorline`

**Comment by skbolton** [comment]
In the end I have decided that I don't want to have too much configuration in this project. Also since users can always override I would rather go with defaults that work for me and for others. This is resolved in #11 by changing the Eclipse color to #585273

**Comment by imajes** [comment]
@skbolton sounds more than reasonable to me. i'm always a fan of documenting it, to help others in the future, but gh search is pretty decent now, so that's not a major issue.

**Comment by skbolton** [comment]
@imajes i am working on a system to produce a change log so that users can undo things where they feel that the theme drifted in their expectations. Would you feel that would help?
